title: UNC
description: UranosNetworkCreation
author: Apilonius64

github_username: UranosNetworkCreation

remote_theme: "dracula/gh-pages"

show_header: true
show_downloads: true

header_pages:
  - index.md

description: "<a href='https://uranosnetworkcreation.github.io/'>Home</a> <a href='https://uranosnetworkcreation.github.io/showcase'>Showcase</a> <a href='https://uranosnetworkcreation.github.io/dev'>How it works</a> <a href='https://uranosnetworkcreation.github.io/story'>Story</a> <a href='https://uranosnetworkcreation.github.io/licenses'>Licenses</a>"

include:
  - _pages

exclude:
  - .gitignore
  - README.md

github:
  zip_url: https://github.com/UranosNetworkCreation/UNC/zipball/main
  tar_url: https://github.com/UranosNetworkCreation/UNC/tarball/main
  repository_url: https://github.com/UranosNetworkCreation/UNC
  Home: "/"