title: UNC
description: UranosNetworkCreation
author: Apilonius64

github_username: UranosNetworkCreation

theme: minima

header_pages:
  - _pages/home.md

include:
  - _pages

exclude:
  - .gitignore
  - README.md