title: UNC
description: UranosNetworkCreation
author: Apilonius64

github_username: UranosNetworkCreation

remote_theme: "dracula/gh-pages"

show_header: true
show_downloads: true

header_pages:
  - index.md

include:
  - _pages

exclude:
  - .gitignore
  - README.md