title: UNC
description: UranosNetworkCreation
author: Apilonius64

github_username: UranosNetworkCreation

remote_theme: pages-themes/architect@v0.2.0

header_pages:
  - index.md

include:
  - _pages

exclude:
  - .gitignore
  - README.md