title: UNC
description: UranosNetworkCreation
author: Apilonius64

github_username: UranosNetworkCreation

remote_theme: "dracula/gh-pages"

show_header: true
show_downloads: true
icon: logo.png

header_pages:
  - index.md

include:
  - _pages

exclude:
  - .gitignore
  - README.md

github:
  zip_url: https://github.com/UranosNetworkCreation/UNC/zipball/main
  tar_url: https://github.com/UranosNetworkCreation/UNC/tarball/main
  Home: "/"