title: UNC
description: UranosNetworkCreation
author: Apilonius64

github_username: UranosNetworkCreation

remote_theme: "dracula/gh-pages"

show_header: true
show_downloads: true

header_pages:
  - index.md

description: "<a href='https://uranosnetworkcreation.github.io/'><u>Home</u></a> <a href='https://uranosnetworkcreation.github.io/showcase'><u>Showcase</u></a> <a href='https://uranosnetworkcreation.github.io/dev'><u>How it works</u></a> <a href='https://uranosnetworkcreation.github.io/story'><u>Story</u></a> <a href='https://uranosnetworkcreation.github.io/licenses'><u>Licenses</u></a>"

include:
  - _pages

exclude:
  - .gitignore
  - README.md

github:
  zip_url: https://github.com/UranosNetworkCreation/UNC/zipball/main
  tar_url: https://github.com/UranosNetworkCreation/UNC/tarball/main
  repository_url: https://github.com/UranosNetworkCreation/UNC
  Home: "/"