title: UNC
description: UranosNetworkCreation
author: Apilonius64

github_username: UranosNetworkCreation

theme: architect

header_pages:
  - index.md

include:
  - _pages

exclude:
  - .gitignore
  - README.md